name: API Regression Tests (ReqRes)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: |
          newman run api-tests/collection.json \
          -e api-tests/environment.json \
          --delay-request 500 \
          --retry-count 3 \
          --reporters cli
